site_name: Pro_110822

use_directory_urls: false

site_description: Pro_110822 documentation
docs_dir: docs # indispensable or readthedocs will fail
theme: 
  name: material
  language: en
  features:
    # - navigation.instant
    # - navigation.tabs
    - toc.integrate
    # - content.tabs.link
  palette:
    scheme: slate
    primary: teal
    accent: teal
repo_url: https://github.com/HamzaBakkour/pro_110822

copyright: © Hamza Bakkour, 2023.
nav:
    - Overview: index.md
    - 'Public interface': 
      - mainwindow.md
      - senduserinput.md
      - reciveuserinput.md
      
    - Tests: tests.md
    - Licence: licence.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings
  - search
  - include-markdown
  - mkdocs-video